[package]
name = "kami"
version = "0.0.1"
authors = ["50ShadesOfCode <killershadow425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="2.33.3"